# Generated by Django 4.2.5 on 2023-12-30 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomDepartement', models.CharField(choices=[('energetique', 'Energetique'), ('cfm', 'CFM'), ('t labo bio', 'T Labo Bio'), ('imp', 'IMP'), ('g info', 'G Info'), ('teb', 'TEB'), ('t labo chimie', 'T Labo Chimie')], max_length=50, verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['-NomDepartement'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.CharField(max_length=5, verbose_name='Matricule')),
                ('Nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('Mail', models.CharField(max_length=100, verbose_name='Email')),
                ('Statut', models.CharField(choices=[('titulaire', 'Titulaire'), ('missionnaire', 'Missionnaire'), ('vacataire', 'Vacataire')], max_length=15, verbose_name='Statut')),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_P16.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['-Matricule'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=50, verbose_name='Login')),
                ('Password', models.CharField(max_length=100, verbose_name='mot de passe')),
                ('Droit', models.CharField(choices=[('second', 'Second'), ('admin', 'Admin')], max_length=20, verbose_name='Droit')),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_P16.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-Login'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(max_length=100, verbose_name='Matière')),
                ('Enseignant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_P16.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['-Libelle'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('Matricule', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('Nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('Prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_P16.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
                'ordering': ['-Matricule'],
            },
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_P16.departement', verbose_name='Département')),
                ('Matiere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='G_P16.matiere', verbose_name='Matière')),
            ],
        ),
    ]
