# Generated by Django 4.2.5 on 2023-12-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='NomDepartement',
            field=models.CharField(choices=[('cfm', 'CFM'), ('t labo bio', 'T Labo Bio'), ('energetique', 'Energetique'), ('imp', 'IMP'), ('g info', 'G Info'), ('t labo chimie', 'T Labo Chimie'), ('teb', 'TEB')], max_length=50, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Droit',
            field=models.CharField(choices=[('admin', 'Admin'), ('second', 'Second')], max_length=20, verbose_name='Droit'),
        ),
    ]
