# Generated by Django 4.2.5 on 2023-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0002_alter_departement_nomdepartement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='NomDepartement',
            field=models.CharField(max_length=50, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Droit',
            field=models.CharField(choices=[('second', 'Second'), ('admin', 'Admin')], max_length=20, verbose_name='Droit'),
        ),
    ]
