# Generated by Django 4.2.5 on 2023-12-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0003_alter_departement_nomdepartement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='Departement',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='G_P16.departement', verbose_name='Département'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('missionnaire', 'Missionnaire'), ('vacataire', 'Vacataire'), ('titulaire', 'Titulaire')], max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Droit',
            field=models.CharField(choices=[('admin', 'Admin'), ('second', 'Second')], max_length=20, verbose_name='Droit'),
        ),
    ]
