# Generated by Django 4.2.5 on 2023-12-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0005_alter_enseignant_departement_alter_enseignant_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('vacataire', 'Vacataire'), ('titulaire', 'Titulaire'), ('missionnaire', 'Missionnaire')], max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='Enseignant',
            field=models.CharField(max_length=10, verbose_name='Enseignant'),
        ),
    ]
