# Generated by Django 4.2.5 on 2023-12-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0007_alter_enseignant_departement_alter_enseignant_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Departement',
            field=models.CharField(max_length=50, verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('titulaire', 'Titulaire'), ('vacataire', 'Vacataire'), ('missionnaire', 'Missionnaire')], max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Droit',
            field=models.CharField(choices=[('second', 'Second'), ('admin', 'Admin')], max_length=20, verbose_name='Droit'),
        ),
    ]
