# Generated by Django 4.2.5 on 2024-01-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0009_alter_enseignant_departement_alter_enseignant_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='semestre',
            field=models.IntegerField(default=10, verbose_name='Semestre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('vacataire', 'Vacataire'), ('missionnaire', 'Missionnaire'), ('titulaire', 'Titulaire')], max_length=15, verbose_name='Statut'),
        ),
        migrations.DeleteModel(
            name='Dispenser',
        ),
    ]
