# Generated by Django 4.2.5 on 2024-01-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0010_matiere_semestre_alter_enseignant_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('titulaire', 'Titulaire'), ('vacataire', 'Vacataire'), ('missionnaire', 'Missionnaire')], max_length=15, verbose_name='Statut'),
        ),
    ]
