# Generated by Django 4.2.5 on 2024-01-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0011_alter_enseignant_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('missionnaire', 'Missionnaire'), ('titulaire', 'Titulaire'), ('vacataire', 'Vacataire')], max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Matricule',
            field=models.CharField(max_length=20, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Droit',
            field=models.CharField(choices=[('second', 'Second'), ('admin', 'Admin')], max_length=20, verbose_name='Droit'),
        ),
    ]
