# Generated by Django 4.2.5 on 2024-01-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0013_alter_enseignant_statut_alter_utilisateur_droit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('vacataire', 'Vacataire'), ('titulaire', 'Titulaire'), ('missionnaire', 'Missionnaire')], max_length=15, verbose_name='Statut'),
        ),
    ]
