# Generated by Django 4.2.5 on 2024-01-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0015_alter_enseignant_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('vacataire', 'Vacataire'), ('missionnaire', 'Missionnaire'), ('titulaire', 'Titulaire')], max_length=15, verbose_name='Statut'),
        ),
    ]
