# Generated by Django 4.2.5 on 2024-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0021_alter_enseignant_statut_alter_matiere_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('titulaire', 'Titulaire'), ('missionnaire', 'Missionnaire'), ('vacataire', 'Vacataire')], max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='Enseignant',
            field=models.CharField(max_length=10, verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Droit',
            field=models.CharField(choices=[('admin', 'Admin'), ('second', 'Second')], max_length=20, verbose_name='Droit'),
        ),
    ]
