# Generated by Django 4.2.5 on 2024-01-07 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0029_alter_enseignant_statut_alter_matiere_enseignant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Statut',
            field=models.CharField(choices=[('missionnaire', 'Missionnaire'), ('vacataire', 'Vacataire'), ('titulaire', 'Titulaire')], max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='Enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='G_P16.enseignant', verbose_name='Enseignant'),
        ),
    ]
