# Generated by Django 4.2.5 on 2024-01-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_P16', '0030_alter_enseignant_statut_alter_matiere_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='Enseignant',
            field=models.CharField(max_length=5, verbose_name='Enseignant'),
        ),
    ]
